workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

stages:
  - all

all:
  stage: all
  script:
    - /bin/true
  after_script:
    - |
      for file in sbom-linux-amd64.spdx.json sbom-linux-amd64.cdx.json \
                  sbom-linux-arm64.spdx.json sbom-linux-arm64.cdx.json \
                  vuln-linux-amd64.json vuln-linux-arm64.json \
                  provenance-linux-amd64.slsa.json provenance-linux-arm64.slsa.json \
                  digests.json cert.json; do
        [ -f "./cibuild-output/${file}" ] || continue
        curl --silent --fail \
          --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
          --upload-file "./cibuild-output/${file}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/supply-chain/${CI_COMMIT_REF_NAME}/${file}"
      done
  tags:
    - cibuilderdev