include:
  - component: $CI_SERVER_FQDN/hrz/container-ci/cibuilder/component-cibuilder/supply-chain-artifacts@main

workflow:
  rules:
    # Trigger rules:
    # The default CI_PIPELINE_SOURCE trigger is schedule
    # Edit or comment in other trigger below

    # Create a pipline on web "Run pipline"
    - if: $CI_PIPELINE_SOURCE == "web"

    # Create a pipline on schedules
    # - if: $CI_PIPELINE_SOURCE == "schedule"

    # Create a pipline on every push commit
    # - if: $CI_PIPELINE_SOURCE == "push"

    # Create a pipeline on merge_requests_event
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # Example: Create pipeline on every push on every branch except main branch
    # - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    #   when: never
    - when: never

stages:
  - all
all:
  extends: .supply-chain-artifacts
  stage: all
  variables:
    CIBUILD_RUN_CMD: all
  script:
    - /bin/true
  tags:
    - cibuilder
