name: cibuilder

on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
  CIBUILD_CI_TOKEN: ${{ secrets.CIBUILD_CI_TOKEN || '' }}
  CIBUILD_BASE_REGISTRY_PASS: ${{ secrets.CIBUILD_BASE_REGISTRY_PASS  || '' }}
  CIBUILD_TARGET_REGISTRY_PASS: ${{ secrets.CIBUILD_TARGET_REGISTRY_PASS  || '' }}
  CIBUILD_BUILD_BUILDKIT_CLIENT_KEY: ${{ secrets.CIBUILD_BUILD_BUILDKIT_CLIENT_KEY  || '' }}
  CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT: ${{ secrets.CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT  || '' }}
  CIBUILD_TEST_SERVICE_ACCOUNT: ${{ secrets.CIBUILD_TEST_SERVICE_ACCOUNT  || '' }}
  CIBUILD_COSIGN_PRIVATE_KEY: ${{ secrets.CIBUILD_COSIGN_PRIVATE_KEY  || '' }}

jobs:

  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: stack4ops/actions-cibuilder@v1
        with:
          image: ghcr.io/stack4ops/cibuilder:build-buildctl@sha256:c9fec7895df5f1705833a1b2d5ebc633b801b44b2a9ee3156feca2922ec87b60
          #bin_ref: main
  
  test:
    needs: build
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v5
      - uses: stack4ops/actions-cibuilder-dind@v1
        with:
          image: ghcr.io/stack4ops/cibuilder:test-docker@sha256:d866829982b55a15105faece5c0abd6f969d55fcd43ac11bb9cecbf938f3f09f
          #bin_ref: main
  
  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: stack4ops/actions-cibuilder@v1
        with:
          image: ghcr.io/stack4ops/cibuilder:release@sha256:1b445bc77dc3f7b0a153eefb2a8ae9b60f610093fbdf48f6c06f50d6fb30e014
          #bin_ref: main
