name: cibuilder

on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
  CIBUILD_CI_TOKEN: ${{ secrets.CIBUILD_CI_TOKEN || '' }}
  CIBUILD_BASE_REGISTRY_PASS: ${{ secrets.CIBUILD_BASE_REGISTRY_PASS  || '' }}
  CIBUILD_TARGET_REGISTRY_PASS: ${{ secrets.CIBUILD_TARGET_REGISTRY_PASS  || '' }}
  CIBUILD_BUILD_BUILDKIT_CLIENT_KEY: ${{ secrets.CIBUILD_BUILD_BUILDKIT_CLIENT_KEY  || '' }}
  CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT: ${{ secrets.CIBUILD_BUILD_BUILDKIT_SERVICE_ACCOUNT  || '' }}
  CIBUILD_TEST_SERVICE_ACCOUNT: ${{ secrets.CIBUILD_TEST_SERVICE_ACCOUNT  || '' }}
  CIBUILD_COSIGN_PRIVATE_KEY: ${{ secrets.CIBUILD_COSIGN_PRIVATE_KEY  || '' }}

jobs:
  all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: stack4ops/actions-cibuilder-dind@v1
        with:
          run_cmd: test
          bin_ref: main
